"use client";

import Link from "next/link";
import { Eye, LockKeyhole, ShieldCheck } from "lucide-react";
import { useState } from "react";

export default function LoginPage() {
  const [show, setShow] = useState(false);
  return <main className="login-page"><section className="login-art"><div className="brand"><div className="brand-mark">A</div><div><div className="brand-name">Clínica Amalia</div><div className="brand-subtitle">Acceso privado</div></div></div><div className="login-copy"><p style={{fontWeight:750,letterSpacing:".14em",textTransform:"uppercase",fontSize:".72rem",opacity:.72}}>Cuidado que se siente</p><h1>Gestión clínica clara y humana.</h1><p style={{maxWidth:480,lineHeight:1.7,opacity:.78}}>Un espacio privado preparado para acompañar la operación odontológica y de armonización facial.</p></div><div style={{position:"relative",zIndex:1,fontSize:".75rem",opacity:.66}}>Entorno demostrativo · Sin pacientes reales</div></section><section className="login-form-wrap"><div className="card login-form"><p className="eyebrow">Bienvenida</p><h2>Iniciar sesión</h2><p className="muted" style={{fontSize:".85rem"}}>Acceso visual preparado para Supabase Auth.</p><form onSubmit={(event)=>event.preventDefault()}><div className="field"><label htmlFor="email">Correo institucional</label><input className="input" id="email" type="email" placeholder="usuario@example.test" autoComplete="email"/></div><div className="field"><label htmlFor="password">Contraseña</label><div style={{position:"relative"}}><input className="input" style={{paddingRight:45}} id="password" type={show?"text":"password"} placeholder="••••••••" autoComplete="current-password"/><button type="button" onClick={()=>setShow(!show)} className="icon-button" aria-label="Mostrar u ocultar contraseña" style={{position:"absolute",right:3,top:1,border:0,background:"transparent"}}><Eye size={18}/></button></div></div><Link href="/dashboard" className="button-primary"><LockKeyhole size={17}/>Entrar a la demostración</Link></form><div className="login-note"><ShieldCheck size={15} style={{display:"inline",marginRight:6}}/>No se autentica ni se almacena información. Auth real se habilitará después de aprobar perfiles, roles y RLS.</div></div></section></main>;
}
